name: Report a bug - create Jira issue

on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
      short_title:
        required: true
        type: string
      description:
        required: true
        type: string
      component:
        required: true
        type: string  

jobs:
  create-entity-in-port-and-update-run:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.ATLASSIANUSEREMAIL }}
          JIRA_API_TOKEN: ${{ secrets.ATLASSIANUSERTOKEN }}

      - name: Transform Inputs to JSON
        id: transform
        run: |
          # Convert comma-separated labels into JSON array
          labels_json=$(echo "${{ inputs.labels }}" | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
          echo "labels=$labels_json" >> $GITHUB_ENV

          # Convert comma-separated components into JSON array of objects
          components_json=$(echo "${{ inputs.components }}" | sed 's/,/","/g' | sed 's/^/{"name":"/' | sed 's/$/"}]/' | sed 's/","/"},{"name":"&/g')
          echo "components=$components_json" >> $GITHUB_ENV

      - name: Debug Transformed Data
        run: |
          echo "Labels: ${{ env.labels }}"
          echo "Components: ${{ env.components }}"

      - name: Log start of Jira issue creation
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
              Creating a new Jira issue.. ⛴️

      - name: Create Jira issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: PORT
          issuetype: Bug
          summary: ${{ inputs.short_title }}
          fields: |
            {
              "labels": ${{ env.labels }},
              "components": ${{ env.components }}
            }
    
      - name: Log issue creation
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          link: https://hadorco.atlassian.net/browse/${{ steps.create.outputs.issue }}
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
             Jira issue created! ✅
           
             The issue id is: ${{ steps.create.outputs.issue }}
